// Damn, it's minified! I you want to have a look go here:
// https://github.com/francescobaldan/Online-MP3-Tag-Editor

$(document).ready(function(){var coverArrayBuffer=null;$("#img").change(function(e){var fileName=e.target.value.split('\\').pop();$("#file-name-img").html("You have chosen: "+fileName);$("#img").prop('disabled',!0);$("label[for='img']").addClass("disabled");$("#locked-img-tooltip").addClass("active");if(this.files.length===0){return}
const reader=new FileReader();reader.onload=function(){coverArrayBuffer=reader.result};reader.onerror=function(){console.error('Reader error',reader.error)};reader.readAsArrayBuffer(this.files[0])});$("#input").change(function(e){var fileName=e.target.value.split('\\').pop();$("#file-name-input").html("You have chosen: "+fileName);$("#input").prop('disabled',!0);$("label[for='input']").addClass("disabled");$("#locked-input-tooltip").addClass("active");if(this.files.length===0){return}
$("#download").click(function(){if($("label[for='input']").hasClass("disabled")){var reader=new FileReader();reader.onload=function(){const arrayBuffer=reader.result;const writer=new ID3Writer(arrayBuffer);var fileName=$("#song-name").val();if($("#song-title").val()!=""){var songTitle=$("#song-title").val();writer.setFrame('TIT2',songTitle)}
if($("#song-artist").val()!=""){var songArtist=$("#song-artist").val();writer.setFrame('TPE1',[songArtist])}
if($("#song-genre").val()!=""){var songGenre=$("#song-genre").val();writer.setFrame('TCON',[songGenre])}
if($("#song-year").val()!=""){var songYear=parseInt($("#song-year").val());writer.setFrame('TYER',songYear)}
if($("#album-name").val()!=""){var albumName=$("#album-name").val();writer.setFrame('TALB',albumName)}
if($("#album-song-nr").val()!=""){var albumSongNr=$("#album-song-nr").val();writer.setFrame('TRCK',albumSongNr)}
if($("#album-song-cd").val()!=""){var albumSongCd=$("#album-song-cd").val();writer.setFrame('TPOS',albumSongCd)}
if(coverArrayBuffer!=null){var songTitle=$("#song-title").val();writer.setFrame('APIC',{type:3,data:coverArrayBuffer,description:songTitle})}
writer.addTag();var blob=writer.getBlob();saveAs(blob,fileName)}
reader.onerror=function(){console.error('Reader error',reader.error)};reader.readAsArrayBuffer($("#input")[0].files[0])}
else{$("#cant-download-tooltip").addClass("active");setTimeout(function(){$("#cant-download-tooltip").removeClass("active")},4500)}})});$(".material-icon-container").on({mouseenter:function(){$("#github-tooltip").addClass("active")},mouseleave:function(){$("#github-tooltip").removeClass("active")}});$(".md-textfield-input").focusin(function(){var name=$(this).attr("id");$("#"+name).addClass("md-textfield-input-active");$("label[for='"+name+"']").addClass("md-textfield-label-active md-texfield-label-has-content")});$(".md-textfield-input").focusout(function(){var name=$(this).attr("id");$("#"+name).removeClass("md-textfield-input-active");if($("#"+name).val()===""){$("label[for='"+name+"']").removeClass("md-texfield-label-has-content")}
$("label[for='"+name+"']").removeClass("md-textfield-label-active")});$("#song-artist").focusin(function(){setTimeout(function(){$("#song-artist-tooltip").addClass("active")},250);setTimeout(function(){$("#song-artist-tooltip").removeClass("active")},4500)});$("#song-artist").focusout(function(){$("#song-artist-tooltip").removeClass("active")});$("#song-genre").focusin(function(){setTimeout(function(){$("#song-genre-tooltip").addClass("active")},250);setTimeout(function(){$("#song-genre-tooltip").removeClass("active")},4500)});$("#song-genre").focusout(function(){$("#song-genre-tooltip").removeClass("active")});$("#song-name").focusin(function(){setTimeout(function(){$("#song-name-tooltip").addClass("active")},250);setTimeout(function(){$("#song-name-tooltip").removeClass("active")},6500)});$("#song-name").focusout(function(){$("#song-name-tooltip").removeClass("active")});$("#album-song-nr").focusin(function(){setTimeout(function(){$("#album-song-nr-tooltip").addClass("active")},250);setTimeout(function(){$("#album-song-nr-tooltip").removeClass("active")},4500)});$("#album-song-nr").focusout(function(){$("#album-song-nr-tooltip").removeClass("active")});$("#album-song-cd").focusin(function(){setTimeout(function(){$("#album-song-cd-tooltip").addClass("active")},250);setTimeout(function(){$("#album-song-cd-tooltip").removeClass("active")},4500)});$("#album-song-cd").focusout(function(){$("#album-song-cd-tooltip").removeClass("active")});$("#another-one").click(function(){window.location='index.html'});$("#github-link").click(function(){window.location='https://github.com/francescobaldan/Online-MP3-Tag-Editor'})})
